name: intellicross_app
description: Mobile App To Program IntelliCross Push Button

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.22.2"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_downloader: ^1.5.2
  path_provider: ^2.0.0-nullsafety
  permission_handler: ^9.2.0
  url_launcher: ^6.0.0-nullsafety.4
  flutter_inappwebview: ^5.3.2
  open_file: ^3.2.1
  file_saver: ^0.1.0
  material_design_icons_flutter: ^5.0.6595
  flutter_blue_plus: ^1.1.3
  wifi_iot: ^0.3.15+2
  # connectivity: ^0.4.5+6
  # flutter_native_splash: ^2.1.6

dev_dependencies:
  flutter_driver:
    sdk: flutter
  pedantic: ^1.8.0

  flutter_native_splash: ^2.1.6

flutter_native_splash:
  android: true
  ios: false
  web : true

  image: assets/images/flutterlogo.png
  color: "#00728f"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/index.html
    - assets/js/
    - assets/css/
    - assets/images/
